# Generated by Django 4.1 on 2022-12-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs')),
                ('description', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('isHome', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('categories', models.ManyToManyField(blank=True, to='blog.category')),
            ],
        ),
    ]
